import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f4f6",
        "on-primary-container": "#eeefff",
        "surface-container-high": "#e7e8ea",
        secondary: "#006c49",
        "secondary-container": "#6cf8bb",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        primary: "#004ac6",
        "on-surface-variant": "#434655",
        "on-primary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f3",
        "surface-dim": "#d9dadc",
        "on-secondary-fixed": "#002113",
        error: "#ba1a1a",
        "on-surface": "#191c1e",
        "surface-bright": "#f8f9fb",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-tertiary-container": "#ffecea",
        background: "#f8f9fb",
        "on-background": "#191c1e",
        "surface-container-highest": "#e1e2e4",
        "inverse-surface": "#2e3132",
        tertiary: "#ab0b1c",
        "on-tertiary-fixed-variant": "#930013",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb3ad",
        surface: "#f8f9fb",
        "tertiary-container": "#cf2c30",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-fixed": "#ffdad7",
        "on-error": "#ffffff",
        "surface-variant": "#e1e2e4",
        "outline-variant": "#c3c6d7",
        outline: "#737686",
        "surface-container": "#edeef0",
        "on-tertiary-fixed": "#410004",
        "surface-tint": "#0053db",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "monospace"],
      },
      // Use Tailwind defaults for borderRadius (rounded-full = 9999px, etc.)
    },
  },
  plugins: [],
};
export default config;
